In [ ]:
import numpy as np
import pandas as pd

file_numbers = [str(i).zfill(2) for i in range(1, 13)]

df_list = []

for num in file_numbers:
    file_path = f'/content/Orders_{num}.csv'
    try:
        df = pd.read_csv(file_path)
        df['Month'] = num
        df_list.append(df)
    except FileNotFoundError:
        print(f"Warning: File not found - {file_path}. Skipping.")

df_orders = pd.concat(df_list, ignore_index=True)

In [ ]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19992 entries, 0 to 19991
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19992 non-null  int64
 1   CustomerID  19992 non-null  int64
 2   ProductID   19806 non-null  float64
 3   OrderDate   19992 non-null  object
 4   Quantity    19770 non-null  float64
 5   Month       19992 non-null  object
dtypes: float64(2), int64(2), object(2)
memory usage: 937.3+ KB

In [ ]:
df_orders[df_orders['Quantity'].isnull()]

       OrderID  CustomerID  ProductID   OrderDate  Quantity Month
158        159         282       16.0  2024-01-03       NaN    01
321        322         162       14.0  2024-01-27       NaN    01
437        438          93        4.0  2024-01-25       NaN    01
439        440         210       15.0  2024-01-18       NaN    01
537        538          81        1.0  2024-01-03       NaN    01
...        ...         ...        ...         ...       ...   ...
19756    19757         145       21.0  12/26/2024       NaN    12
19760    19761         227       19.0  12/27/2024       NaN    12
19878    19879         218       22.0  12/14/2024       NaN    12
19885    19886         247       18.0  19-12-2024       NaN    12
19897    19898          88        3.0  12/23/2024       NaN    12

[222 rows x 6 columns]

In [ ]:
df_cleaned = df_orders.dropna()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  object
dtypes: float64(2), int64(2), object(2)
memory usage: 1.0+ MB

In [ ]:
df_cleaned['OrderDate']

0        2024-01-01
1        2024-01-08
2        2024-01-20
3        2024-01-15
4        2024-01-07
            ...
19987    12/23/2024
19988    12/25/2024
19989    12/18/2024
19990    12/22/2024
19991    12/19/2024
Name: OrderDate, Length: 19586, dtype: object

In [ ]:
df_cleaned['OrderDate'] = df_cleaned['OrderDate'].str.replace('-', '/')

df_cleaned['split_date'] = df_cleaned['OrderDate'].str.split('/')
df_cleaned
df_cleaned['date1'] = df_cleaned['split_date'].str[0]
df_cleaned['date2'] = df_cleaned['split_date'].str[1]
df_cleaned['date3'] = df_cleaned['split_date'].str[2]
df_cleaned.drop(columns=['split_date'], inplace=True)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  object
 6   date1       19586 non-null  object
 7   date2       19586 non-null  object
 8   date3       19586 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.5+ MB

/tmp/ipykernel_2444/2942159442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['OrderDate'] = df_cleaned['OrderDate'].str.replace('-', '/')
/tmp/ipykernel_2444/2942159442.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['split_date'] = df_cleaned['OrderDate'].str.split('/')
/tmp/ipykernel_2444/2942159442.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date1'] = df_cleaned['split_date'].str[0]
/tmp/ipykernel_2444/2942159442.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date2'] = df_cleaned['split_date'].str[1]
/tmp/ipykernel_2444/2942159442.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date3'] = df_cleaned['split_date'].str[2]
/tmp/ipykernel_2444/2942159442.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop(columns=['split_date'], inplace=True)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  object
 6   date1       19586 non-null  object
 7   date2       19586 non-null  object
 8   date3       19586 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.5+ MB

In [ ]:
df_cleaned['Year'] = None
df_cleaned['Day'] = None

/tmp/ipykernel_2444/4286492320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Year'] = None
/tmp/ipykernel_2444/4286492320.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Day'] = None

In [ ]:
df_cleaned['date1']=df_cleaned['date1'].astype(int)
df_cleaned['date2']=df_cleaned['date2'].astype(int)
df_cleaned['date3']=df_cleaned['date3'].astype(int)
df_cleaned['Month']=df_cleaned['Month'].astype(int)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  int64
 6   date1       19586 non-null  int64
 7   date2       19586 non-null  int64
 8   date3       19586 non-null  int64
 9   Year        0 non-null      object
 10  Day         0 non-null      object
dtypes: float64(2), int64(6), object(3)
memory usage: 1.8+ MB

/tmp/ipykernel_2444/757200771.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date1']=df_cleaned['date1'].astype(int)
/tmp/ipykernel_2444/757200771.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date2']=df_cleaned['date2'].astype(int)
/tmp/ipykernel_2444/757200771.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['date3']=df_cleaned['date3'].astype(int)
/tmp/ipykernel_2444/757200771.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Month']=df_cleaned['Month'].astype(int)

In [ ]:
cond1_day = (df_cleaned['date1']>=1) & (df_cleaned['date1']<=31) & (df_cleaned['date1'] != df_cleaned['Month'])
cond2_day = (df_cleaned['date2']>=1) & (df_cleaned['date2']<=31) & (df_cleaned['date2'] != df_cleaned['Month'])
cond3_day = (df_cleaned['date3']>=1) & (df_cleaned['date3']<=31) & (df_cleaned['date3'] != df_cleaned['Month'])
df_cleaned.loc[cond1_day, 'Day'] = df_cleaned.loc[cond1_day, 'date1']
df_cleaned.loc[cond2_day, 'Day'] = df_cleaned.loc[cond2_day, 'date2']
df_cleaned.loc[cond3_day, 'Day'] = df_cleaned.loc[cond3_day, 'date3']
df_cleaned.loc[df_cleaned['date1']>1000, 'Year'] = df_cleaned.loc[df_cleaned['date1']>1000, 'date1']
df_cleaned.loc[df_cleaned['date2']>1000, 'Year'] = df_cleaned.loc[df_cleaned['date2']>1000, 'date2']
df_cleaned.loc[df_cleaned['date3']>1000, 'Year'] = df_cleaned.loc[df_cleaned['date3']>1000, 'date3']
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  int64
 6   date1       19586 non-null  int64
 7   date2       19586 non-null  int64
 8   date3       19586 non-null  int64
 9   Year        19586 non-null  object
 10  Day         18919 non-null  object
dtypes: float64(2), int64(6), object(3)
memory usage: 1.8+ MB

In [ ]:
df_cleaned['Day'].fillna(df_cleaned['Month'], inplace=True)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  int64
 1   CustomerID  19586 non-null  int64
 2   ProductID   19586 non-null  float64
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  int64
 6   date1       19586 non-null  int64
 7   date2       19586 non-null  int64
 8   date3       19586 non-null  int64
 9   Year        19586 non-null  object
 10  Day         19586 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 1.8+ MB

/tmp/ipykernel_2444/1661233022.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Day'].fillna(df_cleaned['Month'], inplace=True)
/tmp/ipykernel_2444/1661233022.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cleaned['Day'].fillna(df_cleaned['Month'], inplace=True)
/tmp/ipykernel_2444/1661233022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Day'].fillna(df_cleaned['Month'], inplace=True)

In [ ]:
df_cleaned.drop(columns=['date1', 'date2', 'date3'], inplace=True)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  object
 1   CustomerID  19586 non-null  object
 2   ProductID   19586 non-null  object
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  int64
 6   Year        19586 non-null  object
 7   Day         19586 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB

/tmp/ipykernel_2444/462352650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop(columns=['date1', 'date2', 'date3'], inplace=True)

In [ ]:
df_cleaned['OrderID'] = df_cleaned['OrderID'].astype(str)
df_cleaned['CustomerID'] = df_cleaned['CustomerID'].astype(str)
df_cleaned['ProductID'] = df_cleaned['ProductID'].astype(str)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19586 entries, 0 to 19991
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     19586 non-null  object
 1   CustomerID  19586 non-null  object
 2   ProductID   19586 non-null  object
 3   OrderDate   19586 non-null  object
 4   Quantity    19586 non-null  float64
 5   Month       19586 non-null  int64
 6   Year        19586 non-null  object
 7   Day         19586 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB

/tmp/ipykernel_2444/852696853.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['OrderID'] = df_cleaned['OrderID'].astype(str)
/tmp/ipykernel_2444/852696853.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['CustomerID'] = df_cleaned['CustomerID'].astype(str)
/tmp/ipykernel_2444/852696853.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['ProductID'] = df_cleaned['ProductID'].astype(str)

In [ ]:
df_cleaned['CleanedDate'] = pd.to_datetime(df_cleaned['Year'].astype(str) + '/' + df_cleaned['Month'].astype(str) + '/' + df_cleaned['Day'].astype(str))
df_cleaned

/tmp/ipykernel_2444/1525807523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['CleanedDate'] = pd.to_datetime(df_cleaned['Year'].astype(str) + '/' + df_cleaned['Month'].astype(str) + '/' + df_cleaned['Day'].astype(str))

,OrderID,CustomerID,ProductID,OrderDate,Quantity,Month,Year,Day,CleanedDate
0,1,202,17.0,2024/01/01,3.0,1,2024,1,2024-01-01
1,2,238,22.0,2024/01/08,9.0,1,2024,8,2024-01-08
2,3,142,7.0,2024/01/20,2.0,1,2024,20,2024-01-20
3,4,9,8.0,2024/01/15,4.0,1,2024,15,2024-01-15
4,5,25,8.0,2024/01/07,1.0,1,2024,7,2024-01-07
...,...,...,...,...,...,...,...,...,...
19987,19988,110,15.0,12/23/2024,4.0,12,2024,23,2024-12-23
19988,19989,18,5.0,12/25/2024,1.0,12,2024,25,2024-12-25
19989,19990,63,21.0,12/18/2024,4.0,12,2024,18,2024-12-18
19990,19991,25,16.0,12/22/2024,4.0,12,2024,22,2024-12-22
19991,19992,178,3.0,12/19/2024,2.0,12,2024,19,2024-12-19

In [ ]:
df_cleaned.to_csv('full_orders_cleaned')

In [3]:
import pandas as pd
df_full=pd.read_csv('full_orders_cleaned.csv')
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19586 entries, 0 to 19585
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   19586 non-null  int64
 1   OrderID      19586 non-null  int64
 2   CustomerID   19586 non-null  int64
 3   ProductID    19586 non-null  float64
 4   OrderDate    19586 non-null  object
 5   Quantity     19586 non-null  float64
 6   Month        19586 non-null  int64
 7   Year         19586 non-null  int64
 8   Day          19586 non-null  int64
 9   CleanedDate  19586 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.5+ MB

In [4]:
df_full

,Unnamed: 0,OrderID,CustomerID,ProductID,OrderDate,Quantity,Month,Year,Day,CleanedDate
0,0,1,202,17.0,2024/01/01,3.0,1,2024,1,2024-01-01
1,1,2,238,22.0,2024/01/08,9.0,1,2024,8,2024-01-08
2,2,3,142,7.0,2024/01/20,2.0,1,2024,20,2024-01-20
3,3,4,9,8.0,2024/01/15,4.0,1,2024,15,2024-01-15
4,4,5,25,8.0,2024/01/07,1.0,1,2024,7,2024-01-07
...,...,...,...,...,...,...,...,...,...,...
19581,19987,19988,110,15.0,12/23/2024,4.0,12,2024,23,2024-12-23
19582,19988,19989,18,5.0,12/25/2024,1.0,12,2024,25,2024-12-25
19583,19989,19990,63,21.0,12/18/2024,4.0,12,2024,18,2024-12-18
19584,19990,19991,25,16.0,12/22/2024,4.0,12,2024,22,2024-12-22
19585,19991,19992,178,3.0,12/19/2024,2.0,12,2024,19,2024-12-19

In [6]:
df_full_drp = df_full.drop(columns=["OrderDate", "Month", "Year", "Day"])
df_full_drp

       Unnamed: 0  OrderID  CustomerID  ProductID  Quantity CleanedDate
0               0        1         202       17.0       3.0  2024-01-01
1               1        2         238       22.0       9.0  2024-01-08
2               2        3         142        7.0       2.0  2024-01-20
3               3        4           9        8.0       4.0  2024-01-15
4               4        5          25        8.0       1.0  2024-01-07
...           ...      ...         ...        ...       ...         ...
19581       19987    19988         110       15.0       4.0  2024-12-23
19582       19988    19989          18        5.0       1.0  2024-12-25
19583       19989    19990          63       21.0       4.0  2024-12-18
19584       19990    19991          25       16.0       4.0  2024-12-22
19585       19991    19992         178        3.0       2.0  2024-12-19

[19586 rows x 6 columns]

In [ ]:
df_full_drp

In [9]:
df_full_drp['CleanedDate'] = pd.to_datetime(df_full_drp['CleanedDate'])
df_full_drp['DayName'] = df_full_drp['CleanedDate'].dt.day_name()
display(df_full_drp.head())
df_full_drp.info()  #the full orders file completely cleaned#

   Unnamed: 0  OrderID  CustomerID  ProductID  Quantity CleanedDate   DayName
0           0        1         202       17.0       3.0  2024-01-01    Monday
1           1        2         238       22.0       9.0  2024-01-08    Monday
2           2        3         142        7.0       2.0  2024-01-20  Saturday
3           3        4           9        8.0       4.0  2024-01-15    Monday
4           4        5          25        8.0       1.0  2024-01-07    Sunday

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19586 entries, 0 to 19585
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   19586 non-null  int64
 1   OrderID      19586 non-null  int64
 2   CustomerID   19586 non-null  int64
 3   ProductID    19586 non-null  float64
 4   Quantity     19586 non-null  float64
 5   CleanedDate  19586 non-null  datetime64[ns]
 6   DayName      19586 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 1.0+ MB

In [11]:
df_products=pd.read_csv('Products.csv')
df_products.info()
df_products

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    25 non-null     int64
 1   ProductName  25 non-null     object
 2   Category     25 non-null     object
 3   Price        25 non-null     object
dtypes: int64(1), object(3)
memory usage: 932.0+ bytes

    ProductID ProductName     Category        Price
0           1      Laptop  Electronics       1,296$
1           2       Phone  Electronics       586.31
2           3      Tablet  Electronics      1369.56
3           4      Camera  Electronics         872$
4           5  Headphones  Electronics  Two Hundred
5           6       Chair    Furniture       437.73
6           7       Table    Furniture       479.86
7           8        Sofa    Furniture        62.67
8           9         Bed    Furniture       713.49
9          10    Wardrobe    Furniture       706.36
10         11       Shirt     Clothing      1702.61
11         12       Pants     Clothing      1472.98
12         13       Dress     Clothing       788.14
13         14      Jacket     Clothing      1256.11
14         15       Shoes     Clothing       1,423$
15         16       Novel        Books        494.4
16         17    Textbook        Books       503.94
17         18    Magazine        Books      1289.58
18         19    Notebook        Books       458.54
19         20      Comics        Books      1313.67
20         21     Car Toy         Toys       1471.8
21         22        Doll         Toys      1979.57
22         23      Puzzle         Toys       1385.0
23         24        Lego         Toys         496$
24         25        Ball         Toys       665.13

In [ ]:
df_products['Price']

In [13]:
df_products.loc[df_products['ProductID'] == 5, 'Price'] = '200'
df_products['Price']

    ProductID ProductName     Category    Price
0           1      Laptop  Electronics   1,296$
1           2       Phone  Electronics   586.31
2           3      Tablet  Electronics  1369.56
3           4      Camera  Electronics     872$
4           5  Headphones  Electronics      200
5           6       Chair    Furniture   437.73
6           7       Table    Furniture   479.86
7           8        Sofa    Furniture    62.67
8           9         Bed    Furniture   713.49
9          10    Wardrobe    Furniture   706.36
10         11       Shirt     Clothing  1702.61
11         12       Pants     Clothing  1472.98
12         13       Dress     Clothing   788.14
13         14      Jacket     Clothing  1256.11
14         15       Shoes     Clothing   1,423$
15         16       Novel        Books    494.4
16         17    Textbook        Books   503.94
17         18    Magazine        Books  1289.58
18         19    Notebook        Books   458.54
19         20      Comics        Books  1313.67
20         21     Car Toy         Toys   1471.8
21         22        Doll         Toys  1979.57
22         23      Puzzle         Toys   1385.0
23         24        Lego         Toys     496$
24         25        Ball         Toys   665.13

In [23]:
df_products['Price'] = df_products['Price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
df_products['Price'] = pd.to_numeric(df_products['Price'])
df_products['Price'] = df_products['Price'].astype(str) + '$'
df_products.drop_duplicates(inplace=True)
df_products['Category'] = df_products['Category'].str.capitalize()
df_products['ProductName'] = df_products['ProductName'].str.capitalize()

In [26]:
df_Customers=pd.read_csv('Customers.csv')
df_Customers.info()
df_Customers['Region']=df_Customers['Region'].str.capitalize()
df_Customers['CustomerName']=df_Customers['CustomerName'].str.capitalize()
df_Customers["CustomerID"].drop_duplicates(inplace=True)
df_Customers

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    300 non-null    int64
 1   CustomerName  300 non-null    object
 2   Region        300 non-null    object
dtypes: int64(1), object(2)
memory usage: 7.2+ KB

     CustomerID    CustomerName      Region
0             1   Laila mahmoud  Alexandria
1             2    Sara ibrahim  Alexandria
2             3    Laila khaled        Giza
3             4    Ahmed hassan  Alexandria
4             5    mona salem      Mansoura
..          ...             ...         ...
295         296       Laila ali       Aswan
296         297   Ahmed mostafa       Aswan
297         298    Ahmed hassan    Mansoura
298         299   Yassin khaled        Giza
299         300     Mona hassan       Aswan

[300 rows x 3 columns]

In [27]:
df_full_drp.to_csv('df_full_drp.csv', index=False)
df_products.to_csv('df_products.csv', index=False)
df_Customers.to_csv('df_Customers.csv', index=False)